### ISSUE TITLE
"SyntaxError: Unexpected token ="

### ISSUE THREAD

**Issue by aaweb** [biesbjerg/ng2-translate-extract#5]
Thanks for this awesome repo.

Unfortunately, I could not get it running?

```
> ng2-translate-extract --dir ./src/client/app/components/frontpage --output ./ --format=json

/Users/andy/workspace/HazuApp/node_modules/@biesbjerg/ng2-translate-extract/dist/utils/translation.collection.js:4
    constructor(values = {}) {
                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/andy/workspace/HazuApp/node_modules/@biesbjerg/ng2-translate-extract/dist/utils/extractor.js:2:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```

I'm using npm version is 4.0.3 and node version v5.6.0. Are there specific versions required by your script? Thanks a lot!

**Comment by biesbjerg** [comment]
Hi!

It seems the issue is because node versions before 6.x does not support default values (`values = {}`) for function args.

I've pushed an update to make it transpile to es5 - can you update and let me know if it works?

**Comment by aaweb** [comment]
I got the following:
```
> ng2-translate-extract --dir ./src/client/app/components/breadcrumb --output ./ --format=json --clean

INFO: Extracting strings from './src/client/app/components/breadcrumb'
ERROR: TypeError: Cannot supply flags when constructing one RegExp from another
```

Upgraded to node version 7.2.1 and it all works fine! Thanks a lot for the quick help.

**Comment by biesbjerg** [comment]
Hi!

Good to hear! 

Node 4.3.2+ support is added via this commit if you need it: https://github.com/biesbjerg/ng2-translate-extract/commit/5c78a37ae0a0c9310fd2b06cfcb4959a64154aed
